### ISSUE TITLE
[Question]:如何让模型能以stream方式输出? 

### ISSUE THREAD

**Issue by zlei0251** [X-PLUG/ChatPLUG#10]

**Comment by rgtjf** [comment]
1. 用作server的时候，stream方式需要server和client之间建立长连接，可以通过[websocket](https://websocket-client.readthedocs.io/en/latest/examples.html)来实现。

2. 模型生成generate过程也需要更新成yield方式，可以学习下[ChatGLM-6B](https://github.com/THUDM/ChatGLM-6B/issues/78)。

3. 目前ChatPLUG steam方式还不支持，会和XDPX deploy一起更新出来。

感谢关注！

**Comment by zlei0251** [comment]
> 1. 用作server的时候，stream方式需要server和client之间建立长连接，可以通过[websocket](https://websocket-client.readthedocs.io/en/latest/examples.html)来实现。
> 2. 模型生成generate过程也需要更新成yield方式，可以学习下[ChatGLM-6B](https://github.com/THUDM/ChatGLM-6B/issues/78)。
> 3. 目前ChatPLUG steam方式还不支持，会和XDPX deploy一起更新出来。
> 
> 感谢关注！

感谢回复，请问大概什么时候会更新这个特性？比较期待

**Comment by rgtjf** [comment]
> > 1. 用作server的时候，stream方式需要server和client之间建立长连接，可以通过[websocket](https://websocket-client.readthedocs.io/en/latest/examples.html)来实现。
> > 2. 模型生成generate过程也需要更新成yield方式，可以学习下[ChatGLM-6B](https://github.com/THUDM/ChatGLM-6B/issues/78)。
> > 3. 目前ChatPLUG steam方式还不支持，会和XDPX deploy一起更新出来。
> > 
> > 感谢关注！
> 
> 感谢回复，请问大概什么时候会更新这个特性？比较期待

预估在6月份
