### ISSUE TITLE
[Question]:可以公开在线demo的角色信息设计吗？

### ISSUE THREAD

**Issue by vhiccup** [X-PLUG/ChatPLUG#11]
在线的demo 中 https://www.modelscope.cn/studios/damo/role_play_chat/summary 可以公开rolejson 数据吗？
另外在线demo中使用的模型是chatplug 3.7B 吗？

**Comment by rgtjf** [comment]
感谢关注！我们在构建角色的benchmark，会包含role json中关于角色的内容，具体设计参考[role-play](https://chatplug.readthedocs.io/zh_CN/latest/roleplay.html)。

在线demo中使用的模型是chatplug 13B，计划开源中。
