### ISSUE TITLE
[Question]: Clarification on the division of full user dialogue history into context and history

### ISSUE THREAD

**Issue by icedpanda** [X-PLUG/ChatPLUG#13]
Hello,

I'm currently studying your code and trying to understand how the full user dialogue history is divided into the short recent dialogue context and the long dialogue history, as described in the corresponding paper.

According to the paper:

> "Besides, to avoid frequently encoding the full user history h, we divide it into a short recent dialogue context c and a long dialogue history l, i.e., h = [c, l], where only the short recent context c will interact with other side information in the encoder."

However, after examining the code, its not clear how this splitting process occurs. Could you provide more information on how this process works? or point to the part of the code that handles this division? Any help or guidance would be greatly appreciated.

Best regards

**Comment by chenhehong** [comment]
Hi, you can reference to https://github.com/X-PLUG/ChatPLUG/blob/main/XDPX/xdpx/utils/chat/pipeline.py#L527C24-L527C24  for inference. As for training phase, see https://github.com/X-PLUG/ChatPLUG/blob/main/XDPX/xdpx/loaders/chat.py#L247C17-L247C17 , here we've split the full history to context and long dialogue history in advance. The variable contents[0] stands for context and contents[1] stands for a string concatenating by history, user_profile, bot_profile and knowledge.

**Comment by icedpanda** [comment]
Hi @chenhehong, thanks for your response. 

However, I still have a bit confusion regarding the splitting of full history into context and long dialogue history during training.

In the training phase code, I noticed that `contents[0]` is assigned to the context and `contents[1]` is assigned to the response. 

If I understand correctly, `contents[2]` likely contains the remaining history, along with `user_profile`, `bot_profile` and `knowledge`. These different components are then further processed and eventually tokenized into `query_token_list`, which is returned by the parse method.

```python
        contents[0] = contents[0].strip().strip(SEP)
        contents[1] = contents[1].strip().strip(SEP)
        contents[2] = contents[2].strip().strip(SEP)

        context = contents[0]
        response = contents[1]
        passages = contents[2].split(';;;')

        context = process_context(context, SEP)
        query_list = []
        for p in passages:
            p = p.strip()
            if len(p) == 0:
                continue
            p = p.strip(";")
            p = p.strip(SEP)
            if p.startswith("history"):
                p = p[len("history:"):]
                p = p.replace(' \t ', SEP).replace('\t', SEP)
                p = process_history(p, SEP)
                p = history_template[random.randint(0, len(history_template) - 1)].format(context=context, history=p)
            elif p.startswith("user_profile"):
                p = p[len("user_profile:"):]
                p = user_profile_template[random.randint(0, len(user_profile_template) - 1)].format(context=context,
                                                                                                    user_profile=p)
            elif p.startswith("bot_profile"):
                p = p[len("bot_profile:"):]
                p = bot_profile_template[random.randint(0, len(bot_profile_template) - 1)].format(context=context,
                                                                                                  bot_profile=p)
            else:
                p = p[len("knowledge:"):]
                p = knowledge_template[random.randint(0, len(knowledge_template) - 1)].format(context=context,
                                                                                              knowledge=p)
            p = p + SEP
            query_list.append(p)
        if len(query_list) == 0:
            p = context_template[random.randint(0, len(context_template) - 1)].format(context=context)
            p = p + SEP
            query_list.append(p)

        response = response + SEP

        query_token_list = [cls._tokenizer.encode(q) for q in query_list]
        response_token = cls._tokenizer.encode(response)

        return {
            'id': _id,
            'query': query_token_list,
            'response': response_token,
        }
```

Could you please confirm whether my understanding is correct, And if so, could you provide some insight into where and how the initial split between the context and the remaining dialogue history (in contents[2]) is performed? From inference, it seems to be 2 https://github.com/X-PLUG/ChatPLUG/blob/ac5e7fa9b63b2f3447e7b88bf00e1d197799c9c1/XDPX/chat_pipeline/chatplug_3.7B_sftv2.6.0_instruction.hjson#L43

Thanks

**Comment by chenhehong** [comment]
Your understanding is correct. And we split context and history offline. That is, if you follow the example https://github.com/X-PLUG/ChatPLUG#one-click-train , you can perform splitting operation at https://github.com/X-PLUG/ChatPLUG/blob/main/data/belle/process_belle_0.5M.py#L12 . However, as the Belle dataset does not have a long history, the `passages` field is empty in the example code.

**Comment by icedpanda** [comment]
Thanks!
