### ISSUE TITLE
[Bug]:关于训练阶段数据预处理逻辑的问题

### ISSUE THREAD

**Issue by vikingmars** [X-PLUG/ChatPLUG#14]
我理解，这里在处理历史对话数据的时候，需要先对"\t"字符做替换
https://github.com/X-PLUG/ChatPLUG/blob/e4e208f6980376183c8b82c1d5e6933248eb9986/XDPX/xdpx/loaders/chat.py#L261
但是，L238  这个@t5_token_process 似乎已经把context 中所有"\t"替换为了'▁<extra_id_33>'，导致上述逻辑不生效
https://github.com/X-PLUG/ChatPLUG/blob/e4e208f6980376183c8b82c1d5e6933248eb9986/XDPX/xdpx/loaders/chat.py#L238

麻烦确认一下这里是不是有些问题~感谢

**Comment by chenhehong** [comment]
感谢关注！`p = p.replace(' \t ', SEP).replace('\t', SEP) ` 是历史遗留下来的脏代码，已移除。感谢~
这里注意history中各个对话文本需要以`</s>`连接。

**Comment by vikingmars** [comment]
> 感谢关注！`p = p.replace(' \t ', SEP).replace('\t', SEP) ` 是历史遗留下来的脏代码，已移除。感谢~ 这里注意history中各个对话文本需要以`</s>`连接。
