### ISSUE TITLE
[Question]:请问persona_benchmark.json的格式是什么样

### ISSUE THREAD

**Issue by dlutzhouyue** [X-PLUG/ChatPLUG#17]
hi，我在项目中找不到persona_benchmark.json。我已经读过[Role-Play](https://chatplug.readthedocs.io/zh_CN/latest/roleplay.html)，但是仍有疑问。我是这样写的，似乎不起作用。

`{"persona": "你是一个大学生，今年21岁，名字叫小婉。 我是你的男学长，你很喜欢我， 你的目标是让我愿意出来跟你约会。"}
{"role_instruction": "请用萌妹子的风格回答， 请多多使用emoji表情。"}`

**Comment by chenhehong** [comment]
你好，persona_benchmark.json文件是我们评测模型人设能力的评测集，没有开源，如果需要自己构建人设评测集，每一行文本可以按照如下格式构建，其中span字段是groud truth，代码会自动计算acc：
{"bot_profile": "我来自甘肃;我叫小何;我非常喜欢凉皮;我喜欢射击;我在集美大学上学;我最喜欢的电影是北京乐与路、中国合伙人、新少林寺;我最喜欢的音乐是屋顶、芳华绝代;我三十一岁;我大学学计算机科学与技术专业;我是狮子座", "usr_profile": "我最喜欢的食物是虾大宴、南瓜粥、特色菜;最近我开始上射箭课，很喜欢;我喜欢听当爱已成往事、思念的距离;我是处女座;我是运动康复专业的;我叫高斌;我在哈尔滨医科大学读书;我最喜欢的电影是罪与罚、奇迹世界、左右情缘;我三十四岁;我来自湖北", "history": ["这电影好看吗？", "一般般吧，感觉不适合我这个年纪看了"], "utterance": "哟，你几岁了？", "span": "31|三十一", "response": "我三十一岁", "type": "年龄", "who": "bot"}
