### ISSUE TITLE
[Feature]:数据开源或者数据获取方式？

### ISSUE THREAD

**Issue by lucasjinreal** [X-PLUG/ChatPLUG#18]
数据开源或者数据获取方式？

**Comment by chenhehong** [comment]
你好，公开数据集可以参考论文的数据引用的来源，部分数据集为我们自建数据集，暂时没有开源

**Comment by lucasjinreal** [comment]
公开数据readme里面没有表明，哪个数据集呢

**Comment by chenhehong** [comment]
可以直接参考一下我们论文中相应数据集的引用文献https://arxiv.org/abs/2304.07849
