### ISSUE TITLE
论文写的实在是太不清晰了

### ISSUE THREAD

**Issue by David-Lee-1990** [X-PLUG/ChatPLUG#19]
- 用了哪些通用指令数据？比例是多少？
- 微调的对话数据是多少？
- 哪些数据导致了模型的对话的personalize上效果更好？
- 不使用FiD是否更好？现在LLM的长度应该是够的。

**Comment by chenhehong** [comment]
- 通用指令数据10w条左右，比例差不多20%
- 微调的对话数据在50w条左右
- 哪些数据导致了模型的对话的personalize上效果更好：可以参考论文的Persona Grounded Data部分
- 不使用FiD效果差不多，但在开启互联网搜索增强并且检索文档较多的情况下，推理速度慢一些
