### ISSUE TITLE
[Bug]:The model will return wrong or duplicate data

### ISSUE THREAD

**Issue by kdy1999** [X-PLUG/ChatPLUG#8]
![image](https://github.com/X-PLUG/ChatPLUG/assets/30910741/16377f43-c5f4-4645-b4bd-149d7e6345ed)
As shown in the figure, use XDPX-based one-click inference

**Comment by xuguohai** [comment]
There is a bug in the data processing pipeline. We will work on fixing it as soon as possible.

**Comment by rgtjf** [comment]
@kdy1999 the issue has been fixed. You can now pull from the latest branch.
