### ISSUE TITLE
[Question]:配置完毕以后，执行的时候出这个问题，不知道是不是少文件了

### ISSUE THREAD

**Issue by hjzhang75** [X-PLUG/ChatPLUG#9]
File "/home/xxx/ChatPLUG/XDPX/scripts/fidchat_new.py", line 21, in <module>
    from xdpx.utils.chat.openweb_search import Snippet
ModuleNotFoundError: No module named 'xdpx.utils.chat.openweb_search

File "/home/xxx/ChatPLUG/XDPX/xdpx/utils/chat/pipeline.py", line 26, in <module>
    from xdpx.utils.chat.openkg_retrieval import OpenKG
ModuleNotFoundError: No module named 'xdpx.utils.chat.openkg_retrieval'
或者是我少装了什么包？

**Comment by rgtjf** [comment]
问题已经修复了，可以 `git pull` 拉下main最新版本。

最近我们在开发`openweb_search` & `openkg_retrieval`导致这两个文件缺失的，万分抱歉。
